spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.frontend-url=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Rate Limiting (same as dev)
security.rate-limit.login.attempts=5
security.rate-limit.login.window=60
security.rate-limit.refresh.attempts=10
security.rate-limit.refresh.window=60
security.rate-limit.max-buckets=100000

# Token Security
security.token-cleanup.enabled=true
security.token-cleanup.retention-hours=2
security.token-cleanup.interval=3600000

# JWT
jwt.access-token.expiration-ms=900000
jwt.refresh-token.expiration-ms=604800000
jwt.secret.key=${JWT_SECRET}

# OAuth2 - GITHUB
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# OAuth2 - GOOGLE
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.jpa.properties.hibernate.default_batch_fetch_size=100
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}